package com.example.myapplication;

import java.util.List;

public class CountryListCreator {

    public static void CreateCountryList(List<PlaceItem> listOfCountries) {
        listOfCountries.add(new PlaceItem(R.drawable.afghanistan, "Afghanistan"));
        listOfCountries.add(new PlaceItem(R.drawable.albania, "Albania"));
        listOfCountries.add(new PlaceItem(R.drawable.algeria, "Algeria"));
        listOfCountries.add(new PlaceItem(R.drawable.andorra, "Andorra"));
        listOfCountries.add(new PlaceItem(R.drawable.angola, "Angola"));
        listOfCountries.add(new PlaceItem(R.drawable.antigua, "Antigua and Barbuda"));
        listOfCountries.add(new PlaceItem(R.drawable.argentina, "Argentina"));
        listOfCountries.add(new PlaceItem(R.drawable.armenia, "Armenia"));
        listOfCountries.add(new PlaceItem(R.drawable.aruba, "Aruba"));
        listOfCountries.add(new PlaceItem(R.drawable.australia, "Australia"));
        listOfCountries.add(new PlaceItem(R.drawable.austria, "Austria"));
        listOfCountries.add(new PlaceItem(R.drawable.azerbijan, "Azerbijan"));
        listOfCountries.add(new PlaceItem(R.drawable.bahamas, "Bahamas"));
        listOfCountries.add(new PlaceItem(R.drawable.bahrain, "Bahrain"));
        listOfCountries.add(new PlaceItem(R.drawable.bangladesh, "Bangladesh"));
        listOfCountries.add(new PlaceItem(R.drawable.barbados, "Barbados"));
        listOfCountries.add(new PlaceItem(R.drawable.belarus, "Belarus"));
        listOfCountries.add(new PlaceItem(R.drawable.belgium, "Belgium"));
        listOfCountries.add(new PlaceItem(R.drawable.benin, "Benin"));
        listOfCountries.add(new PlaceItem(R.drawable.bolivia, "Bolivia"));
        listOfCountries.add(new PlaceItem(R.drawable.bosnia, "Bosnia and Herzegovina"));
        listOfCountries.add(new PlaceItem(R.drawable.botswana, "Botswana"));
        listOfCountries.add(new PlaceItem(R.drawable.brazil, "Brazil"));
        listOfCountries.add(new PlaceItem(R.drawable.bulgaria, "Bulgaria"));
        listOfCountries.add(new PlaceItem(R.drawable.burkina_faso, "Burkina Faso"));
        listOfCountries.add(new PlaceItem(R.drawable.cambodia, "Cambodia"));
        listOfCountries.add(new PlaceItem(R.drawable.cameroon, "Cameroon"));
        listOfCountries.add(new PlaceItem(R.drawable.canada, "Canada"));
        listOfCountries.add(new PlaceItem(R.drawable.central_africa, "Central African Republic"));
        listOfCountries.add(new PlaceItem(R.drawable.chad, "Chad"));
        listOfCountries.add(new PlaceItem(R.drawable.chile, "Chile"));
        listOfCountries.add(new PlaceItem(R.drawable.china, "China"));
        listOfCountries.add(new PlaceItem(R.drawable.colombia, "Colombia"));
        listOfCountries.add(new PlaceItem(R.drawable.congo, "Congo"));
        listOfCountries.add(new PlaceItem(R.drawable.congo_rep, "Congo [Republic]"));
        listOfCountries.add(new PlaceItem(R.drawable.costa_rica, "Costa Rica"));
        listOfCountries.add(new PlaceItem(R.drawable.croatia, "Croatia"));
        listOfCountries.add(new PlaceItem(R.drawable.cuba, "Cuba"));
        listOfCountries.add(new PlaceItem(R.drawable.cyprus, "Cyprus"));
        listOfCountries.add(new PlaceItem(R.drawable.czech, "Czech Republic"));
        listOfCountries.add(new PlaceItem(R.drawable.denemark, "Denmark"));
        listOfCountries.add(new PlaceItem(R.drawable.dominican_republic, "Dominican Republic"));
        listOfCountries.add(new PlaceItem(R.drawable.ecuador, "Ecuador"));
        listOfCountries.add(new PlaceItem(R.drawable.egypt, "Egypt"));
        listOfCountries.add(new PlaceItem(R.drawable.el_salvador, "El Salvador"));
        listOfCountries.add(new PlaceItem(R.drawable.england, "England"));
        listOfCountries.add(new PlaceItem(R.drawable.equatorial_guinea, "Equatorial Guinea"));
        listOfCountries.add(new PlaceItem(R.drawable.erithrea, "Eritrea"));
        listOfCountries.add(new PlaceItem(R.drawable.estonia, "Estonia"));
        listOfCountries.add(new PlaceItem(R.drawable.ethiopia, "Ethiopia"));
        listOfCountries.add(new PlaceItem(R.drawable.faroe_islands, "Faroe Islands"));
        listOfCountries.add(new PlaceItem(R.drawable.fiji, "Fiji"));
        listOfCountries.add(new PlaceItem(R.drawable.finland, "Finland"));
        listOfCountries.add(new PlaceItem(R.drawable.france, "France"));
        listOfCountries.add(new PlaceItem(R.drawable.gabon, "Gabon"));
        listOfCountries.add(new PlaceItem(R.drawable.georgia, "Georgia"));
        listOfCountries.add(new PlaceItem(R.drawable.germany, "Germany"));
        listOfCountries.add(new PlaceItem(R.drawable.ghana, "Ghana"));
        listOfCountries.add(new PlaceItem(R.drawable.gibraltar, "Gibraltar"));
        listOfCountries.add(new PlaceItem(R.drawable.greece, "Greece"));
        listOfCountries.add(new PlaceItem(R.drawable.grenada, "Grenada"));
        listOfCountries.add(new PlaceItem(R.drawable.guam, "Guam"));
        listOfCountries.add(new PlaceItem(R.drawable.guatemala, "Guatemala"));
        listOfCountries.add(new PlaceItem(R.drawable.guinea, "Guinea"));
        listOfCountries.add(new PlaceItem(R.drawable.guinea_bissau, "Guinea-Bissau"));
        listOfCountries.add(new PlaceItem(R.drawable.guyana, "Guyana"));
        listOfCountries.add(new PlaceItem(R.drawable.haiti, "Haiti"));
        listOfCountries.add(new PlaceItem(R.drawable.honduras, "Honduras"));
        listOfCountries.add(new PlaceItem(R.drawable.hong_kong, "Hong Kong"));
        listOfCountries.add(new PlaceItem(R.drawable.hungary, "Hungary"));
        listOfCountries.add(new PlaceItem(R.drawable.iceland, "Iceland"));
        listOfCountries.add(new PlaceItem(R.drawable.india, "India"));
        listOfCountries.add(new PlaceItem(R.drawable.indonesia, "Indonesia"));
        listOfCountries.add(new PlaceItem(R.drawable.iran, "Iran"));
        listOfCountries.add(new PlaceItem(R.drawable.iraq, "Iraq"));
        listOfCountries.add(new PlaceItem(R.drawable.ireland, "Ireland"));
        listOfCountries.add(new PlaceItem(R.drawable.israel, "Israel"));
        listOfCountries.add(new PlaceItem(R.drawable.italy, "Italy"));
        listOfCountries.add(new PlaceItem(R.drawable.ivory_coast, "Ivory Coast"));
        listOfCountries.add(new PlaceItem(R.drawable.jamaica, "Jamaica"));
        listOfCountries.add(new PlaceItem(R.drawable.japan, "Japan"));
        listOfCountries.add(new PlaceItem(R.drawable.jordan, "Jordan"));
        listOfCountries.add(new PlaceItem(R.drawable.kazakhstan, "Kazakhstan"));
        listOfCountries.add(new PlaceItem(R.drawable.kenya, "Kenya"));
        listOfCountries.add(new PlaceItem(R.drawable.kosovo, "Kosovo"));
        listOfCountries.add(new PlaceItem(R.drawable.kuwait, "Kuwait"));
        listOfCountries.add(new PlaceItem(R.drawable.kyrgyzstan, "Kyrgyzstan"));
        listOfCountries.add(new PlaceItem(R.drawable.laos, "Laos"));
        listOfCountries.add(new PlaceItem(R.drawable.latvia, "Latvia"));
        listOfCountries.add(new PlaceItem(R.drawable.lebanon, "Lebanon"));
        listOfCountries.add(new PlaceItem(R.drawable.liberia, "Liberia"));
        listOfCountries.add(new PlaceItem(R.drawable.libya, "Libya"));
        listOfCountries.add(new PlaceItem(R.drawable.lithuania, "Lithuania"));
        listOfCountries.add(new PlaceItem(R.drawable.luxembourg, "Luxemburg"));
        listOfCountries.add(new PlaceItem(R.drawable.macau, "Macau"));
        listOfCountries.add(new PlaceItem(R.drawable.macedonia, "Macedonia [FYROM]"));
        listOfCountries.add(new PlaceItem(R.drawable.madagascar, "Madagascar"));
        listOfCountries.add(new PlaceItem(R.drawable.malaysia, "Malaysia"));
        listOfCountries.add(new PlaceItem(R.drawable.mali, "Mali"));
        listOfCountries.add(new PlaceItem(R.drawable.malta, "Malta"));
        listOfCountries.add(new PlaceItem(R.drawable.mexico, "Mexico"));
        listOfCountries.add(new PlaceItem(R.drawable.micronesia, "Micronesia"));
        listOfCountries.add(new PlaceItem(R.drawable.moldova, "Moldova"));
        listOfCountries.add(new PlaceItem(R.drawable.monaco, "Monaco"));
        listOfCountries.add(new PlaceItem(R.drawable.mongolia, "Mongolia"));
        listOfCountries.add(new PlaceItem(R.drawable.montenegro, "Montenegro"));
        listOfCountries.add(new PlaceItem(R.drawable.morocco, "Morocco"));
        listOfCountries.add(new PlaceItem(R.drawable.mozambique, "Mozambique"));
        listOfCountries.add(new PlaceItem(R.drawable.myanmar, "Myanmar"));
        listOfCountries.add(new PlaceItem(R.drawable.namibia, "Namibia"));
        listOfCountries.add(new PlaceItem(R.drawable.nepal, "Nepal"));
        listOfCountries.add(new PlaceItem(R.drawable.netherlands, "Netherlands"));
        listOfCountries.add(new PlaceItem(R.drawable.new_zealand, "New Zealand"));
        listOfCountries.add(new PlaceItem(R.drawable.nicaragua, "Nicaragua"));
        listOfCountries.add(new PlaceItem(R.drawable.niger, "Niger"));
        listOfCountries.add(new PlaceItem(R.drawable.nigeria, "Nigeria"));
        listOfCountries.add(new PlaceItem(R.drawable.northern_ireland, "Northern Ireland"));
        listOfCountries.add(new PlaceItem(R.drawable.north_korea, "North Korea"));
        listOfCountries.add(new PlaceItem(R.drawable.norway, "Norway"));
        listOfCountries.add(new PlaceItem(R.drawable.oman, "Oman"));
        listOfCountries.add(new PlaceItem(R.drawable.pakistan, "Pakistan"));
        listOfCountries.add(new PlaceItem(R.drawable.panama, "Panama"));
        listOfCountries.add(new PlaceItem(R.drawable.papua, "Papua New Guinea"));
        listOfCountries.add(new PlaceItem(R.drawable.paraguay, "Paraguay"));
        listOfCountries.add(new PlaceItem(R.drawable.peru, "Peru"));
        listOfCountries.add(new PlaceItem(R.drawable.philippines, "Philippines"));
        listOfCountries.add(new PlaceItem(R.drawable.poland, "Poland"));
        listOfCountries.add(new PlaceItem(R.drawable.portugal, "Portugal"));
        listOfCountries.add(new PlaceItem(R.drawable.puerto_rico, "Puerto Rico"));
        listOfCountries.add(new PlaceItem(R.drawable.qatar, "Qatar"));
        listOfCountries.add(new PlaceItem(R.drawable.romania, "Romania"));
        listOfCountries.add(new PlaceItem(R.drawable.russia, "Russia"));
        listOfCountries.add(new PlaceItem(R.drawable.rwanda, "Rwanda"));
        listOfCountries.add(new PlaceItem(R.drawable.san_marino, "San Marino"));
        listOfCountries.add(new PlaceItem(R.drawable.saudi_arabia, "Saudi Arabia"));
        listOfCountries.add(new PlaceItem(R.drawable.scotland, "Scotland"));
        listOfCountries.add(new PlaceItem(R.drawable.senegal, "Senegal"));
        listOfCountries.add(new PlaceItem(R.drawable.serbia, "Serbia"));
        listOfCountries.add(new PlaceItem(R.drawable.singapore, "Singapore"));
        listOfCountries.add(new PlaceItem(R.drawable.slovakia, "Slovakia"));
        listOfCountries.add(new PlaceItem(R.drawable.slovenia, "Slovenia"));
        listOfCountries.add(new PlaceItem(R.drawable.somalia, "Somalia"));
        listOfCountries.add(new PlaceItem(R.drawable.south_africa, "South Africa"));
        listOfCountries.add(new PlaceItem(R.drawable.south_korea, "South Korea"));
        listOfCountries.add(new PlaceItem(R.drawable.spain, "Spain"));
        listOfCountries.add(new PlaceItem(R.drawable.switzerland, "Switzerland"));
        listOfCountries.add(new PlaceItem(R.drawable.syria, "Syria"));
        listOfCountries.add(new PlaceItem(R.drawable.taiwan, "Taywan"));
        listOfCountries.add(new PlaceItem(R.drawable.tanzania, "Tansania"));
        listOfCountries.add(new PlaceItem(R.drawable.thailand, "Thailand"));
        listOfCountries.add(new PlaceItem(R.drawable.togo, "Togo"));
        listOfCountries.add(new PlaceItem(R.drawable.trinidad, "Trinidad and Tobago"));
        listOfCountries.add(new PlaceItem(R.drawable.tunisia, "Tunisia"));
        listOfCountries.add(new PlaceItem(R.drawable.turkey, "Turkey"));
        listOfCountries.add(new PlaceItem(R.drawable.turkmenistan, "Turkmenistan"));
        listOfCountries.add(new PlaceItem(R.drawable.uganda, "Uganda"));
        listOfCountries.add(new PlaceItem(R.drawable.ukraine, "Ukraine"));
        listOfCountries.add(new PlaceItem(R.drawable.uae, "United Arab Emirates"));
        listOfCountries.add(new PlaceItem(R.drawable.uk, "UK"));
        listOfCountries.add(new PlaceItem(R.drawable.usa, "USA"));
        listOfCountries.add(new PlaceItem(R.drawable.uruguay, "Uruguay"));
        listOfCountries.add(new PlaceItem(R.drawable.uzbekistan, "Uzbekistan"));
        listOfCountries.add(new PlaceItem(R.drawable.vatican, "Vatican"));
        listOfCountries.add(new PlaceItem(R.drawable.venezuela, "Venezuela"));
        listOfCountries.add(new PlaceItem(R.drawable.vietnam, "Vietnam"));
        listOfCountries.add(new PlaceItem(R.drawable.wales, "Wales"));
        listOfCountries.add(new PlaceItem(R.drawable.yemen, "Yemen"));
        listOfCountries.add(new PlaceItem(R.drawable.zambya, "Zambia"));
        listOfCountries.add(new PlaceItem(R.drawable.zimbabwe, "Zimbabwe"));
    }
}
